--DROP TABLE AACSYT CASCADE CONSTRAINTS
CREATE TABLE AACSYT
(
    MACSYT VARCHAR2(10) PRIMARY KEY,
    TENCSYT NVARCHAR2(100),
    DCCSYT NVARCHAR2(100),
    SDTCSYT CHAR(10)
);

--DROP TABLE AANHANVIEN CASCADE CONSTRAINTS
CREATE TABLE AANHANVIEN
(
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN NVARCHAR2(50),
    PHAI NVARCHAR2(3),
    NGAYSINH DATE,
    CMND CHAR(10),
    QUEQUAN NVARCHAR2(100),
    SODT CHAR(10),
    CSYT VARCHAR2(10),
    VAITRO NVARCHAR2(20),
    CHUYENKHOA NVARCHAR2(50)
);

--DROP TABLE AAKHOA CASCADE CONSTRAINTS
CREATE TABLE AAKHOA
(
    TENKHOA NVARCHAR2(50) PRIMARY KEY
);

--DROP TABLE AABENHNHAN CASCADE CONSTRAINTS
CREATE TABLE AABENHNHAN
(
    MABN VARCHAR2(10) PRIMARY KEY,
    MACSYT VARCHAR2(10),
    TENBN NVARCHAR2(50),
    CMND CHAR(10),
    NGAYSINH DATE,
    SONHA CHAR(10),
    TENDUONG NVARCHAR2(60),
    QUANHUYEN NVARCHAR2(30),
    TINHTP NVARCHAR2(30),
    TIENSUBENH NVARCHAR2(200),
    TIENSUBENHGD NVARCHAR2(200),
    DIUNGTHUOC NVARCHAR2(500)
);

--DROP TABLE AAHSBA CASCADE CONSTRAINTS
CREATE TABLE AAHSBA
(
    MAHSBA VARCHAR2(10) PRIMARY KEY,
    MABN VARCHAR(10),
    NGAY DATE,
    CHUANDOAN NVARCHAR2(200),
    MABS VARCHAR2(10),
    MAKHOA NVARCHAR2(50),
    MACSYT VARCHAR2(10),
    KETLUAN NVARCHAR2(200)
);

--DROP TABLE AAHSBA_DV CASCADE CONSTRAINTS
CREATE TABLE AAHSBA_DV
(
    MAHSBA VARCHAR2(10),
    MADV VARCHAR2(10),
    NGAY DATE,
    MAKTV VARCHAR2(10),
    KETQUA NVARCHAR2(200),
    PRIMARY KEY(MAHSBA, MADV, NGAY)
);

ALTER TABLE AAHSBA
ADD CONSTRAINT FK_HSBA_BENHNHAN FOREIGN KEY (MABN) REFERENCES AABENHNHAN(MABN);
ALTER TABLE AAHSBA
ADD CONSTRAINT FK_HSBA_NHANVIEN FOREIGN KEY (MABS) REFERENCES AANHANVIEN(MANV);
ALTER TABLE AAHSBA
ADD CONSTRAINT FK_HSBA_CSYT FOREIGN KEY (MACSYT) REFERENCES AACSYT(MACSYT);
ALTER TABLE AAHSBA
ADD CONSTRAINT FK_HSBA_KHOA FOREIGN KEY (MAKHOA) REFERENCES AAKHOA(TENKHOA);

ALTER TABLE AANHANVIEN
ADD CONSTRAINT FK_NHANVIEN_CSYT FOREIGN KEY (CSYT) REFERENCES AACSYT(MACSYT);
ALTER TABLE AANHANVIEN
ADD CONSTRAINT FK_NHANVIEN_KHOA FOREIGN KEY (CHUYENKHOA) REFERENCES AAKHOA(TENKHOA);

ALTER TABLE AABENHNHAN
ADD CONSTRAINT FK_BENHNHAN_CSYT FOREIGN KEY (MACSYT) REFERENCES AACSYT(MACSYT);

ALTER TABLE AAHSBA_DV
ADD CONSTRAINT FK_HSBA_DV_HSBA FOREIGN KEY (MAHSBA) REFERENCES AAHSBA(MAHSBA);
ALTER TABLE AAHSBA_DV
ADD CONSTRAINT FK_HSBA_DV_NHANVIEN FOREIGN KEY (MAKTV) REFERENCES AANHANVIEN(MANV);


ALTER TABLE AANHANVIEN
ADD CONSTRAINT CHECK_PHAI CHECK (PHAI = N'Nam' OR PHAI = N'Nu');


--CREATE USER NHANVIEN
CREATE OR REPLACE PROCEDURE usp_CreateUserNV
AS
    CURSOR CUR IS (SELECT MANV
                    FROM AANHANVIEN
                    WHERE MANV NOT IN (SELECT USERNAME
                                        FROM ALL_USERS));
    strSQL VARCHAR(2000);
    Usr varchar2(30);
BEGIN
    OPEN CUR;
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE';
    EXECUTE IMMEDIATE (strSQL);
    LOOP
        FETCH CUR INTO Usr;
        EXIT WHEN CUR%NOTFOUND;
        
        strSQL:= 'CREATE USER '||Usr||' IDENTIFIED BY '||Usr;
        EXECUTE IMMEDIATE (strSQL);
        strSQL:= 'GRANT CREATE SESSION TO '||Usr;
        EXECUTE IMMEDIATE (strSQL);
    END LOOP;
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=FALSE';
    EXECUTE IMMEDIATE (strSQL);
END;

EXECUTE usp_CreateUserNV;

--CREATE USER BENHNHAN
CREATE OR REPLACE PROCEDURE usp_CreateUserBN
AS
    CURSOR CUR IS (SELECT MABN
                    FROM AABENHNHAN
                    WHERE MABN NOT IN (SELECT USERNAME
                                        FROM ALL_USERS));
    strSQL VARCHAR(2000);
    Usr varchar2(30);
BEGIN
    OPEN CUR;
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE';
    EXECUTE IMMEDIATE (strSQL);
    LOOP
        FETCH CUR INTO Usr;
        EXIT WHEN CUR%NOTFOUND;
        
        strSQL:= 'CREATE USER '||Usr||' IDENTIFIED BY '||Usr;
        EXECUTE IMMEDIATE (strSQL);
        strSQL:= 'GRANT CREATE SESSION TO '||Usr;
        EXECUTE IMMEDIATE (strSQL);
    END LOOP;
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=FALSE';
    EXECUTE IMMEDIATE (strSQL);
END;

EXECUTE usp_CreateUserBN;


--TAO ROLE TRONG HE THONG
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE ROLE THANHTRA;
CREATE ROLE BENHNHAN;
CREATE ROLE NVCSYT;
CREATE ROLE GD;
CREATE ROLE GDCSYT;
CREATE ROLE BACSI;
CREATE ROLE NGHIENCUU;
ALTER SESSION SET "_ORACLE_SCRIPT"=FALSE;

--CREATE ROLE THANH TRA
CREATE OR REPLACE PROCEDURE usp_priv_ThanhTraUser
AS
        CURSOR CUR IS (SELECT MANV
                    FROM AANHANVIEN 
                    WHERE VAITRO = 'Thanh tra');
        Usr varchar2(30);
        strSQL VARCHAR(2000);
BEGIN
    OPEN CUR;
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE';
    EXECUTE IMMEDIATE (strSQL);
    LOOP
        FETCH CUR INTO Usr;
        EXIT WHEN CUR%NOTFOUND;
        
        strSQL := 'GRANT THANHTRA TO '||Usr;
        EXECUTE IMMEDIATE (strSQL);
    END LOOP;
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=FALSE';
    EXECUTE IMMEDIATE (strSQL);
END;

EXECUTE usp_priv_ThanhTraUser;
GRANT SELECT ON AANHANVIEN TO THANHTRA;


--CREATE ROLE Y SI/BAC SI
CREATE OR REPLACE PROCEDURE usp_grantRole_YBSUser
AS
        CURSOR CUR IS (SELECT MANV
                    FROM AANHANVIEN 
                    WHERE VAITRO = 'Y Si/Bac Si');
        Usr varchar2(30);
        strSQL VARCHAR(2000);
BEGIN
    OPEN CUR;
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE';
    EXECUTE IMMEDIATE (strSQL);
    LOOP
        FETCH CUR INTO Usr;
        EXIT WHEN CUR%NOTFOUND;
        
        strSQL := 'GRANT BACSI TO '||Usr;
        EXECUTE IMMEDIATE (strSQL);
    END LOOP;
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=FALSE';
    EXECUTE IMMEDIATE (strSQL);
END;

EXECUTE usp_grantRole_YBSUser;


--CREATE ROLE CO SO Y TE
CREATE OR REPLACE PROCEDURE usp_grantRole_CSYTUser
AS
        CURSOR CUR IS (SELECT MANV
                    FROM AANHANVIEN 
                    WHERE VAITRO = 'Co so y te');
        Usr varchar2(30);
        strSQL VARCHAR(2000);
BEGIN
    OPEN CUR;
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE';
    EXECUTE IMMEDIATE (strSQL);
    LOOP
        FETCH CUR INTO Usr;
        EXIT WHEN CUR%NOTFOUND;
        
        strSQL := 'GRANT NVCSYT TO '||Usr;
        EXECUTE IMMEDIATE (strSQL);
    END LOOP;
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=FALSE';
    EXECUTE IMMEDIATE (strSQL);
END;

EXECUTE usp_grantRole_CSYTUser;


--CREATE ROLE NGHIEN CUU
CREATE OR REPLACE PROCEDURE usp_grantRole_NCUser
AS
        CURSOR CUR IS (SELECT MANV
                    FROM AANHANVIEN 
                    WHERE VAITRO = 'Nghien cuu');
        Usr varchar2(30);
        strSQL VARCHAR(2000);
BEGIN
    OPEN CUR;
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE';
    EXECUTE IMMEDIATE (strSQL);
    LOOP
        FETCH CUR INTO Usr;
        EXIT WHEN CUR%NOTFOUND;
        
        strSQL := 'GRANT NGHIENCUU TO '||Usr;
        EXECUTE IMMEDIATE (strSQL);
    END LOOP;
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=FALSE';
    EXECUTE IMMEDIATE (strSQL);
END;

EXECUTE usp_grantRole_NCUser;

--CREATE ROLE BENH NHAN
CREATE OR REPLACE PROCEDURE usp_priv_BenhNhanUser
AS
        CURSOR CUR IS (SELECT MABN
                    FROM AABENHNHAN);
        Usr varchar2(30);
        strSQL VARCHAR(2000);
BEGIN
    OPEN CUR;
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE';
    EXECUTE IMMEDIATE (strSQL);
    LOOP
        FETCH CUR INTO Usr;
        EXIT WHEN CUR%NOTFOUND;
        
        strSQL := 'GRANT BENHNHAN TO '||Usr;
        EXECUTE IMMEDIATE (strSQL);
    END LOOP;
    strSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT"=FALSE';
    EXECUTE IMMEDIATE (strSQL);
END;

EXECUTE usp_priv_BenhNhanUser;

----TC#3
--THEM, XOA DONG TREN HSBA
CREATE OR REPLACE VIEW UV_THONGTINHSBA
AS
SELECT HSBA.*
FROM AAHSBA HSBA JOIN AANHANVIEN NV ON HSBA.MACSYT = NV.CSYT AND NV.VAITRO = 'Co so y te'
WHERE NV.MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');

GRANT SELECT, INSERT, DELETE ON DNHLAN.UV_THONGTINHSBA TO NVCSYT;


--THEM, XOA DONG DICH VU LIEN QUAN DEN 1 HSBA
CREATE OR REPLACE VIEW UV_THONGTINHSBA_DV
AS
SELECT DV.*
FROM AAHSBA HSBA JOIN AAHSBA_DV DV ON HSBA.MAHSBA = DV.MAHSBA
                 JOIN AANHANVIEN NV ON HSBA.MACSYT = NV.CSYT AND NV.VAITRO = 'Co so y te'
WHERE NV.MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');

GRANT SELECT, INSERT, DELETE ON DNHLAN.UV_THONGTINHSBA_DV TO NVCSYT;


----TC#4
--Y SI/BAC SI XEM HSBA MA HO DA CHUA TRI
CREATE OR REPLACE VIEW UV_YBSXEMTHONGTINHSBA
AS
SELECT HSBA.*
FROM AAHSBA HSBA JOIN AANHANVIEN NV ON HSBA.MABS = NV.MANV AND NV.VAITRO = 'Y Si/Bac Si'
WHERE NV.MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');

GRANT SELECT ON DNHLAN.UV_YBSXEMTHONGTINHSBA TO BACSI;


--Y SI/BAC SI XEM KET QUA CAC DICH VU HO DA SU DUNG
CREATE OR REPLACE VIEW UV_YBSXEMKQHSBA_DV
AS
SELECT DV.MAHSBA, DV.KETQUA
FROM AAHSBA HSBA JOIN AAHSBA_DV DV ON HSBA.MAHSBA = DV.MAHSBA
                 JOIN AANHANVIEN NV ON HSBA.MABS = NV.MANV AND NV.VAITRO = 'Y Si/Bac Si'
WHERE NV.MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');

GRANT SELECT ON DNHLAN.UV_YBSXEMKQHSBA_DV TO BACSI;


--Y SI/BAC SI XEM HO SO BENH NHAN MA HO DA CHUA TRI
CREATE OR REPLACE VIEW UV_YBSXEMTHONGTINBN
AS
SELECT BN.*
FROM AAHSBA HSBA JOIN AABENHNHAN BN ON HSBA.MABN = BN.MABN
                 JOIN AANHANVIEN NV ON HSBA.MABS = NV.MANV AND NV.VAITRO = 'Y Si/Bac Si'
WHERE NV.MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');

GRANT SELECT ON DNHLAN.UV_YBSXEMTHONGTINBN TO BACSI;


----TC#5

---NGHIEN CUU XEM THONG TIN HSBA CUNG CO SO 
CREATE OR REPLACE VIEW UV_NCXEMTHONGTINHSBA
AS
SELECT HSBA.*
FROM AAHSBA HSBA JOIN AANHANVIEN NV ON HSBA.MACSYT = NV.CSYT AND HSBA.MAKHOA = NV.CHUYENKHOA
WHERE NV.MANV = SYS_CONTEXT('userenv', 'session_user');

GRANT SELECT ON DNHLAN.UV_NCXEMTHONGTINHSBA TO NGHIENCUU;

---NGHIEN CUU XEM THONG TIN HSBA_DV CUNG CO SO 
CREATE OR REPLACE VIEW UV_NCXEMTHONGTINHSBA_DV
as
SELECT DV.*
FROM AAHSBA HSBA JOIN AANHANVIEN NV ON HSBA.MACSYT = NV.CSYT AND HSBA.MAKHOA = NV.CHUYENKHOA
                 JOIN AAHSBA_DV DV ON DV.MAHSBA = HSBA.MAHSBA
WHERE NV.MANV = SYS_CONTEXT('userenv', 'session_user');

GRANT SELECT ON DNHLAN.UV_NCXEMTHONGTINHSBA_DV TO NGHIENCUU;


----TC#6

CREATE OR REPLACE VIEW UV_XEMTHONGTINNHANVIEN
AS
SELECT AANHANVIEN.*
FROM AANHANVIEN  WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');

GRANT SELECT ON DNHLAN.UV_XEMTHONGTINNHANVIEN TO NVCSYT, BACSI, NGHIENCUU;

CREATE OR REPLACE VIEW UV_XEMTHONGTINBENHNHAN
AS
SELECT AABENHNHAN.*
FROM AABENHNHAN  WHERE MABN = SYS_CONTEXT('USERENV', 'SESSION_USER');

GRANT SELECT ON DNHLAN.UV_XEMTHONGTINBENHNHAN TO BENHNHAN;

CREATE OR REPLACE TRIGGER Trigg_NHANVIEN
INSTEAD OF UPDATE ON DNHLAN.UV_XEMTHONGTINNHANVIEN
BEGIN
    UPDATE DNHLAN.AANHANVIEN
    SET HOTEN = :new.HOTEN, PHAI = :new.PHAI, NGAYSINH = :new.NGAYSINH, CMND = :new.CMND, QUEQUAN = :new.QUEQUAN, 
        SODT = :new.SODT, CSYT = :new.CSYT, VAITRO = :new.VAITRO, CHUYENKHOA = :new.CHUYENKHOA 
    WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');
END;
/
CREATE OR REPLACE TRIGGER Trigg_BENHNHAN
INSTEAD OF UPDATE ON DNHLAN.UV_XEMTHONGTINBENHNHAN
BEGIN
    UPDATE DNHLAN.AABENHNHAN
    SET MACSYT = :new.MACSYT,
        TENBN = :new.TENBN, 
        CMND = :new.CMND, 
        NGAYSINH = :new.NGAYSINH, 
        SONHA = :new.SONHA, 
        TENDUONG = :new.TENDUONG, 
        QUANHUYEN = :new.QUANHUYEN, 
        TINHTP = :new.TINHTP, 
        TIENSUBENH = :new.TIENSUBENH, 
        TIENSUBENHGD = :new.TIENSUBENHGD, 
        DIUNGTHUOC = :new.DIUNGTHUOC
    WHERE MABN = SYS_CONTEXT('USERENV', 'SESSION_USER');
END;


